package:
  format-version: "1.0.0"
  name: "net_apps_pic32cz_ca70"
  type: "application"
  status: "production"
  required: false
  version: "v1.0.0"
  
  dependencies:
    - name: "net"
      type: "package"
      version: "v3.13.0"
    - name: "core"
      type: "package"
      version: "v3.14.0"
    - name: "csp"
      type: "package"
      version: "v3.20.0"
    - name: "bsp"
      type: "package"
      version: "v3.21.1"
    - name: "crypto"
      type: "package"
      version: "v3.8.2"
    - name: "wolfMQTT"
      type: "package"
      version: "v1.11.1"